theme: cayman
title: Play with Python
description: A fun way to learn python
include:
  - index.md
  - installPython.md
  - pythonfirststeps.md
  - scalartypes.md
  - collections.md
  - copying.md
  - comprehensions.md
  - funcs.md
  - list_quiz.md
  - scopes.md

plugins:
  - jemoji
