site_name: Play with python

nav:
  - Home: index.md
  - Python Installation: installPython.md
  - Github account: createGithub.md
  - Python First steps: pythonfirststeps.md
  - Scalar Data Types: scalartypes.md
  - Collections: collections.md
  - Shallow Copy and Deep Copy: copying.md
  - Comprehensions: comprehensions.md
  - Functions: funcs.md
  - Variable Scopes: scopes.md

theme:
  name: readthedocs
  custom_dir: themes
